[project]
name = "moodemoji"
version = "0.1.0"
description = "Map moods to emojis ğŸ˜"
authors = [
  { name = "Vedanta Barooah", email = "barooah.io@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }

[project.urls]
Homepage = "https://github.com/yourusername/moodemoji"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
